### ISSUE TITLE
When using multiple tabs, onIdle seems to trigger when it should not

### ISSUE THREAD

**Issue by mattjneuber** [SupremeTechnopriest/react-idle-timer#165]
I'm experiencing strange behavior where after `onIdle` triggers the first time, and subsequently calling `reset()`, events in the browser are not preventing `onIdle` from triggering again, but only if I have multiple tabs open with `emitOnAllTabs` set to true, and using `stopOnIdle`.  The same thing happens if I don't use `stopOnIdle` but manually call `pause()` in `onIdle` and `resume()` in my modal's button handler.

I made up a small code sandbox to reproduce the issue: https://codesandbox.io/s/determined-minsky-jo7h1?file=/src/App.js

1. Load up the sandbox in two tabs/windows 
2. Wait until 'stay on' button shows up, click it
3. Notice that the other window changes back to 'content', which is good
4. Now move your mouse around in the first window and even though you are moving your mouse, the 'stay on' button will show up after 10 more seconds.

This does not seem to happen with the same code if only one tab is open.
One thing I observed is that if I check `getRemainingTime()` inside `onIdle`, the second time it will have a value that is > 0, which makes it seem like something internally is resetting the time correctly, but `onIdle` is still getting fired when it should not be.

As an aside, I'm also open to input on doing this whole thing differently if there is an established pattern for showing a modal with "log out" and "stay logged in" that automatically logs out after n seconds.  I initially was going to try using state, but it seems that state updates do not appear in `onIdle`.  It'll always have the initial value.

**Comment by SupremeTechnopriest** [comment]
Thanks for the report.  I will look into this.

**Comment by SupremeTechnopriest** [comment]
@mattjneuber Pretty sure I found and patched this issue.  I published `4.6.3-rc.1` to npm under the `next` tag.  Install it with `npm i react-idle-timer@next` and let me know if that fixes your issue.

**Comment by mattjneuber** [comment]
I updated the above code sandbox with the new version, but it still doesn't seem to work.  Same exact behavior as before there.
I also can no longer run my actual application (built with webpack) after updating to the new version, it's complaining like so:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at index.es.js:1
    at Module.../../../node_modules/react-idle-timer/dist/index.es.js (index.es.js:1)
```

I don't have that problem with the previous version.

**Comment by SupremeTechnopriest** [comment]
Hmm yeah there was a CSP issue with regeneratorRuntime eval that I tried patching in this version.  Let me fix that and ill update you here when its done.  Which browser are you using to test?

**Comment by mattjneuber** [comment]
I'm using Chrome on Mac.

**Comment by SupremeTechnopriest** [comment]
@mattjneuber  

Hmmm i cant seem to get that error to happen in the sandbox.  I published `4.6.3-rc.2` where I try transforming the runtime again.  Could you test on your end?

**Comment by mattjneuber** [comment]
rc2 does allow me to build and run my application again, and allowed me to verify that the behavior described in the first post still occurs there.

Thanks for working with me on this.

**Comment by SupremeTechnopriest** [comment]
Sure no problem.  I see the issue.  Working on it now.

**Comment by SupremeTechnopriest** [comment]
@mattjneuber can you try `4.6.3-rc.3`?

**Comment by mattjneuber** [comment]
That seems to have fixed it!

**Comment by SupremeTechnopriest** [comment]
Beautiful!  Just waiting for a response from one other person regarding an issue and I will get this rolled out!  Thanks again for the report.

**Comment by initin** [comment]
using 4.6.3-rc.3.

I am experiencing the same behavior. I have implemented exact same thing as @mattjneuber's sandbox.

Here are some steps,
I have two tabs open, tab A and tab B.
Timeout is 10 seconds. once `onIdle` triggers, and click on 'stay on' ( `reset()` ). 
After that moving mouse in tab A for more then 10 seconds, then go on tab B. and moving mouse, `onIdle` will trigger in both tabs.
Event not getting `onAction` trigger in tab B if I am not active for more then 10 seconds(timeout).

Thanks for the Library.

**Comment by SupremeTechnopriest** [comment]
@initin Sounds like you aren't focusing the second window. Can you try it again and make sure the window has focus?

**Comment by initin** [comment]
Yes, window is in focus. Even I am pressing left and right clicks in window and doing other activity.

**Comment by SupremeTechnopriest** [comment]
If you are using `stopOnIdle` you wont get any events if you are idle, even `onAction`. Can you make a sandbox with your exact use case?  Ive tested the fix and @mattjneuber confirmed it works.  There must be something different about the configuration.

**Comment by initin** [comment]
https://codesandbox.io/s/intelligent-frost-76eu8?file=/src/App.js

here is the sandbox, forked from @mattjneuber's . 

I have added `onAction` count, to just check event triggers or not. open 2 tabs. once 'stay on' clicked, try to move mouse tab A, and don't do any action in tab B for 5 seconds. then do action in tab B, `onAction` will not trigger and after 5 sec on tab B, `onIdle` will trigger on both tabs.

**Comment by SupremeTechnopriest** [comment]
@initin Thanks for the sandbox.  I can confirm the issue.  Let me work on this today and get back to you.

**Comment by SupremeTechnopriest** [comment]
@initin updating to the latest release candidate seems to have done the trick.  Check this fork and make sure its working for you. 

https://codesandbox.io/s/blissful-goldwasser-90mws

**Comment by SupremeTechnopriest** [comment]
Did you have a chance to confirm this?  Im planning on rolling it out today.

**Comment by SupremeTechnopriest** [comment]
This patch has been published to `4.6.3` on the `latest` tag.  If you are still experiencing problems feel free to re open this or create another issue.

**Comment by initin** [comment]
sorry for the delay, was not able to test. I will test it today and let you know. Thanks.

**Comment by initin** [comment]
> 
> 
> @initin updating to the latest release candidate seems to have done the trick. Check this fork and make sure its working for you.
> 
> https://codesandbox.io/s/blissful-goldwasser-90mws

@SupremeTechnopriest still experiencing the issue in this sandbox

**Comment by initin** [comment]
![idle-lib-error](https://user-images.githubusercontent.com/11597697/120061571-83391a00-c07b-11eb-8a92-4320234b0b2a.PNG)
![idle-lib-error1](https://user-images.githubusercontent.com/11597697/120061572-83d1b080-c07b-11eb-9687-27288d842845.PNG)

also getting this error while opening / refreshing my app.

**Comment by SupremeTechnopriest** [comment]
Yeah that error was happening for someone else too.  It's related to hot reload but never actually happens in production. 

For the other issue I'll need some additional info as I can not seem to reproduce it.  For starters, what browser are you testing in and on which operating system?

**Comment by initin** [comment]
Web browser is - Firefox 88.0.1 (64-bit)
OS - Windows 10

**Comment by initin** [comment]
@SupremeTechnopriest any updates on this?

**Comment by SupremeTechnopriest** [comment]
@initin Sorry work got really busy.  Its on my list.  Hopefully ill be able to take a look this weekend.
